### PR TITLE
[WIP] get_share() to retrieve share information about known share (by id)

### PR DESCRIPTION
**Pull request by soalhn**
@PVince81: Any comments about this? (#7) Because I don't know if it's a right approach :wink:

### CODE REVIEW

**Comment by soalhn** [comment]
Done d02c3410875b8dc33632635ed6434481a8dc677e

**Comment by soalhn** [comment]
Do you know what's wrong with tests @ owncloud 6?
I'm running them locally (ownCloud installed @ VM on separate server) and they are working fine.

**Comment by PVince81** [comment]
Possibly race conditions in OC 6... seems to happen randomly.
I'll try and review your PR later this week. :smile:

**Comment by PVince81** [comment]
Nice work! The unit tests run fine for me on your branch against stable6, stable7 and master.

A few points:
- [ ] Please remove the following attributes, as they are useless for API consumers:
 - item_type
 - item_source
 - parent
 - rename "stime" to "share_time" (it's clearer)
 - storage
 - mail_send
- [ ] I think `get_with` and `get_type` should be removed ? Not sure if these convenience methods are really needed, especially that there are already lots of other methods.
- [ ] Add python docs for the ShareInfo methods (I can help if needed as I might be more familiar with what they represent)
- [ ] remove PublicShare and UserShare classes if possible and replace with ShareInfo. But I suspect that share_with_link doesn't get a full ShareInfo instance, is that correct ? (we can also address this separately as it's more tricky)

**Comment by soalhn** [comment]
> * [x] Please remove the following attributes, as they are useless for API consumers:

Ok, I've removed it (appropriate methods also) by purging them on class __init__ method.

> * [x] I think get_with and get_type should be removed?

I've only created them as shorter version of get_share_type() and get_share_with() - but I agree with you and they have been removed :wink:

> * [ ] Add python docs for the ShareInfo methods (I can help if needed as I might be more familiar with what they represent)

I will try do it in next step.

> * [ ] remove PublicShare and UserShare classes if possible and replace with ShareInfo. But I suspect that share_with_link doesn't get a full ShareInfo instance, is that correct ? (we can also address this separately as it's more tricky)

Yes, I'll do it as separate PR.

**Comment by soalhn** [comment]
Ok, I have to admit, that the task to add python docs is beyond my experience and in addition I don't have my spare time for the project anymore :confused:
I think that the PR was my last contribution to the project so far (but maybe it will change in the indefinite future) - I'm very sorry about that :worried:
So feel free to take over the task.

**Comment by PVince81** [comment]
No worries, I fully understand. Thanks for letting me know.

I hope you had fun all along! And thanks for having pushed the sharing stuff forward, I appreciate it :-)

Feel free to drop by if you'd like to contribute again at some point in the future.

I will take over the PR once I find some time after the upcoming OC 8 release.

**Comment by PVince81** [comment]
Created a local branch to be able to continue working on this task: https://github.com/PVince81/pyocclient/pull/69

**Pull request closed without merging**
